/**
 * Generates src/app/environments/environment.ts from process.env.
 * On Vercel (VERCEL=1) all required vars must be present or the build fails.
 * Locally it keeps your existing environment.ts unless FORCE_ENV_GENERATE=1.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = join(root, 'src/app/environments/environment.ts');

const isVercel = process.env.VERCEL === '1';
const force = process.env.FORCE_ENV_GENERATE === '1';

if (!isVercel && !force && existsSync(outPath)) {
  console.log('[generate-env] Local environment.ts found — skipped.');
  process.exit(0);
}

const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
  'YOUTUBE_API_KEY',
];

const missing = required.filter((key) => !process.env[key]?.trim());

if (missing.length) {
  console.error(
    '[generate-env] Missing environment variables:\n  - ' + missing.join('\n  - '),
  );
  console.error(
    '\nIn Vercel: Project → Settings → Environment Variables\n' +
      'Local: set FORCE_ENV_GENERATE=1 and export the vars, or copy environment.example.ts',
  );
  process.exit(1);
}

const str = (key, fallback = '') => JSON.stringify(process.env[key]?.trim() || fallback);

const content = `// Auto-generated by scripts/generate-env.mjs — do not edit by hand on Vercel.
export const environment = {
  production: true,
  firebaseConfig: {
    apiKey: ${str('FIREBASE_API_KEY')},
    authDomain: ${str('FIREBASE_AUTH_DOMAIN')},
    projectId: ${str('FIREBASE_PROJECT_ID')},
    storageBucket: ${str('FIREBASE_STORAGE_BUCKET')},
    messagingSenderId: ${str('FIREBASE_MESSAGING_SENDER_ID')},
    appId: ${str('FIREBASE_APP_ID')},
    measurementId: ${str('FIREBASE_MEASUREMENT_ID')},
  },
  youtubeApiKey: ${str('YOUTUBE_API_KEY')},
};
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, content, 'utf8');
console.log('[generate-env] Wrote', outPath);
